### ISSUE TITLE
Color-coding the Curriculums

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/organizers#114]
In addition to #113 I thought it might be awesome if the workshoppers would get a "color" that makes it easier to visually spot what you are learning. Those color codes could be used in the UI of the workshopper, the labels of the issue in [discussions](https://github.com/nodeschool/discussions/labels) and for badges/stickers etc.

![nodeschool-colors](https://cloud.githubusercontent.com/assets/914122/5692161/2bf8d194-992d-11e4-9464-dff4def479fd.png)

[Download the Illustrator file](https://www.dropbox.com/s/r3oe52ohfowwfmh/NodeSchool-colors.ai?dl=0)

**Comment by Sequoia** [comment]
I might suggest that there are so many clustered in language & node.js (the bulk of the subject matter of nodeschool.io) that I suspect the discussions issue list might just be a blur of yellow & burnt orange. This would diminish the value of tagging imo; seems better to reserve the most visual difference for the most common tags: if learnyounode & stream-adventure are the most common it would not be very useful to give them almost identical colors. (i.e. it would make it harder to scan for stream-adventure tickets).

The more I consider the cost/benefit here, it doesn't seem useful (to me) to try to group these lessons on a color wheel. Uniform sticker/label colors is fine but that can be achieved without color wheel grouping. What is the specific benefit of the latter?

Thank you for working on thinking about this, @martinheidegger!! I hope I don't come off as too critical :smile_cat:

**Comment by martinheidegger** [comment]
Not too critical at all! I value the input very much. Particularly since I am wondering about a better distribution as well.

The reason why I started thinking about this was the situation with the labels: 

![screenshot 2015-01-21 01 37 42](https://cloud.githubusercontent.com/assets/914122/5821291/2c0c2f12-a10e-11e4-955c-5f0870446939.png)

The colors are not helpful at all! The reason for the color wheel is to suggest a practical closeness similar color = similar category making it easier to identify what a person is interested in: Having many blue/green stickers would mean web focus. Having many violet/red stickers would mean the person is  interested in science/theory. The amount of colors in the terminal is limited which is why I chose so similar colors. Also I chose all in the same saturation spectrum because then you can set secondary colors that are brighter/darker.

**Comment by martinheidegger** [comment]
@Sequoia You mentioned a color coding based on popularity. I see that problematic since popularity can change over time.

Also it is possible to color-code based on age (which was first) but that would not make much sense to me since the age is very arbitrary and doesn't give the user any benefit.

It could also be possible to assign levels based on "complexity" (beginners/advanced) but I realised that the complexity only really helps in the first tasks (core). Its hard to objectively say that levelmeup is *more difficult* than makemehapi.

**Comment by Sequoia** [comment]
So is the usecase for these color schemes primarily "distinguishing the interests of one nodeschool user who purchased multiple nodeschool laptop stickers from the interests another nodeschool user who purchased multiple nodeschool laptop stickers?"  For this application I get your colorscheme, but I'm not convinced the scenario described is one we need to worry too much about.

What I *am* interested in is the current use of the colors, which is to make issues easier to scan visually in the issues list & to make labels easy to find in the labels list.  To this end I think we should be using the gamut of colors maximally: it makes more sense to make our top most commonly used tags Red, Green, and Blue (for high contrast/easy scanning) rather than Yellow, Light Yellow, Dark Yellow.  The latter makes it harder to find the labels & harder to scan issue lists.

To put it as a user story, "*As a nodeschool helper, I want to be able to quickly and easily find & identify the most common labels*." I don't think a gradient of burnt orange to marigold serves this purpose.  Surely there's another user story "*As a sticker-enthusiast I want to be able to identify the interests of other sticker enthusiasts*" & surely that's valid, but I would want to weigh that hypothetical user's needs against the current needs of existing "helper" users.

This may be a side issue but currently the tags are so redundant & similar color-wise that they're pretty hard to scan as is. Can we change them so e.g. all "consider closing" type tags are red, all "workshop-name" type tags are blue etc.?  This would potentially make it much easier to scan. 40 similar shades of pastel... well it doesn't really help me personally.

Regarding stickers, I say do whatever you like! :+1: If stickers & tag colors don't match up it's nbd, I think brand-compliance is a fairly low priority in the nodeschool community (at least I hope it is!). :smile_cat:

**Comment by martinheidegger** [comment]
I didn't *just* propose it for the recognition of stickers on a notebook (that was just an example). I think of it as a didactic way to let people know what kind of section in the NodeSchool world they are interacting with. The math books in my school had a different color than the geography books, etc. Or the book edges of o`reilly books http://archive.oreilly.com/pub/post/the_mystery_behind_our_spine_c.html (you need to scroll a little in this link) 

Here is an article that could be helpful:
http://www.thebestofteacherentrepreneurs.net/2013/06/accelerated-reader-color-coded-and-book.html

Imagine this situation: A user goes to the NodeSchool site. Sees the section "Language" that is *yellow* and installs `javascripting`. The `javascripting` ui is of the same color that he just saw on the website (assuring him that he just installed the right thing). Then he has a problem and tries to post something on the discussions board and there the label has the same color. Creating a deeper relationship in his head (probably subconscious).

Also coloring helps for orientation. People can not just see that they are in a section but immediately understand: "There are sections!" Reminds me a bit of color coding in buildings:
http://www.designboom.com/architecture/ralston-bau-signage-design-for-government-building-norway/


You are right, being able to distinguish important labels from one another is important this issue needs a new proposal that considers:

- [ ] Colors for things (labels) that are not "workshoppers" (like the windows label)
- [ ] Color distribution that makes it easier to distinguish importance of a *thing*

I am not really agreeing with the importance setting per se because it will hopefully change over time and then we are stuck with color codes.

**Comment by martinheidegger** [comment]
Closing this issue for now. Anybody feel free to reopen it with new ideas.
