### ISSUE TITLE
Request to be added as owner

### ISSUE THREAD

**Issue by Cairo-HackerSpace** [nodeschool/organizers#150]
Hi this is Waleed and we are a HackerSpace/community based in Cairo, Egypt(http://cairohackerspace.org/). 
We started in 2009, following the open-source methodology ever since. 
We would like to start a nodeschool chapter which I'll be co-organizing with Tarek Ahmed (https://github.com/tou2). 
We have been big fans of Node.js for quite a while now and would like to set up meet-ups and events for other Node.js enthusiastists in Egypt.

Stay awesome!
Waleed

**Comment by maxogden** [comment]
Hi Waleed,

Thanks for your interest!

We already have some people active in Cairo: https://github.com/orgs/nodeschool/teams/cairo

You should open an issue on their repository here https://github.com/nodeschool/cairo and see about collaborating with them directly

**Comment by Cairo-HackerSpace** [comment]
Max,

Thanks for the quick response! 

The thing is we are looking to expand to cover all Egypt not just Cairo. So we are partnering up with a few of other HackerSpaces in other cities we got Alex and Dahab and we are contacting other HackerSpaces as well. Just so it will be more nation-wide, rich and structured.

The bigger the community, the more knowledge. :)

So how do we proceed from here?

**Comment by maxogden** [comment]
@Cairo-HackerSpace hi Waleed,

So far with our chapters we try to keep them focused on one city at a time, so each city that has groups who want to host events registers their own chapter. For example, Australia does some events like this: https://github.com/nodeschool/discussions/issues/294 the "Australia NodeSchool Day", but they leave the individual organizing up to each city chapter.

Since there are already some active people in Cairo they should definitely be part of the discussion here as well. cc @nodeschool/cairo

I am not sure the best answer. Maybe some other organizers have ideas/feedback too? I would probably recommend starting with chapters for each city that wants to host events, and then as the community in those cities grow we can choose how to handle a nationwide Egypt chapter in the future when we have had more time to discuss national nodeschool chapters.

**Comment by Cairo-HackerSpace** [comment]
That sounds awesome! We are really excited about that and can't wait to start. Our community alone has over 5000 members in our HackerSpace. We'll contact the existing chapter in Cairo and bounce ideas off one another. So let's start by creating a chapter for Giza and Alexandria first, since these are the areas where our events take place. Then we'll see where we can got from there. Also you can check our website for past events as well, if you are interested.

**Comment by maxogden** [comment]
@Cairo-HackerSpace OK I invited you to be an owner, you can now continue following the instructions in the readme in this repo. woohoo!

Also one suggestion, is maybe Giza/Cairo could start out as being the same NodeSchool chapter and just use https://github.com/nodeschool/cairo as the repo for that for the time being. After you run a couple events it will be easier to make decisions on the best way to organize I think.
