### ISSUE TITLE
Ledet Training nodeschool chapter request

### ISSUE THREAD

**Issue by sjledet** [nodeschool/organizers#171]
Hi, I would like to start a nodeschool chapter for Ledet Training. I am @sjledet on twitter and work at Ledet Training, an Adobe Authorized Training Center with locations in six US cities. I will be co-organizing this chapter with my contract trainers. I am new to node.js personally, but plan to offer commercial training courses on the technology in our training centers. *

**Comment by martinheidegger** [comment]
@sjledet The Nodeschool chapters are intentionally place based. Can you create a chapter for every place that you will be. If there is a chapter in a particular city then there is no need to create a chapter there imho.

**Comment by sjledet** [comment]
The issue is that I won't have six different chapters or even two. Would you feel the same way if a larger enterprise asked to have a custom nodeschool? 

----- On Mar 15, 2015, at 1:49 AM, Martin Heidegger <notifications@github.com> wrote: 



@sjledet The Nodeschool chapters are intentionally place based. Can you create a chapter for every place that you will be. If there is a chapter in a particular city then there is no need to create a chapter there imho.

**Comment by martinheidegger** [comment]
I am not sure I made myself clear: A "chapter" is a term that describes the nodeschool activity at a place. It is not related to a company or an organisation. The data that is collected during chapter creation is the list of people that you can talk to at this place about node and nodeschool. This way people that attend at the various places are able to help organize just one place and make it themselves.

**Comment by sjledet** [comment]
If you were trying to develop a node.js training initiative for a commercial training enterprise with 6 company locations and an online presence as well (live, instructor-led, not prerecorded), what would you do then? I am the only one currently involved in the initiative at my organization and i don't want to administer 7 different githubs for the customized version of the node.js courseware I plan on working on. 

It seems like you may be suggesting that's not something that nodeschool would support? I certainly don't want to push rope and try something that would be contrary to your intentions. 

----- On Mar 15, 2015, at 9:28 AM, Martin Heidegger <notifications@github.com> wrote: 



I am not sure I made myself clear: A "chapter" is a term that describes the nodeschool activity at a place. It is not related to a company or an organisation. The data that is collected during chapter creation is the list of people that you can talk to at this place about node and nodeschool. This way people that attend at the various places are able to help organize just one place and make it themselves.

**Comment by jasonrhodes** [comment]
You are absolutely welcome to use the NodeSchool curriculum and materials however you like. Fork any repo or create your own, then use them for whatever you're company is trying to do. Chapters, up to now, have been location based, usually free or low cost community-run orgs that have events on a semi-regular basis in one geographic area. So your use case might not be a chapter but you don't need to be a chapter to use nodeschool materials. 

Does that make sense?

**Comment by martinheidegger** [comment]
I totally agree that its too hard to organise 6 groups all by yourself. That is why a chapter request usually has more than one person organising it. NodeSchool is community organised in other words you build your community with other people from that area. My suggestion (also to easy your workload) would be to find people in each city that help you.

**Comment by jasonrhodes** [comment]
Honestly, @martinheidegger, I don't think this use case is a great one for multiple chapters. 

> a commercial training enterprise with 6 company locations and an online presence as well

No reason the nodeschool materials can't just be used without needing to set up chapter repos, which I think would be misleading.

**Comment by sjledet** [comment]
Agreed. Which is why I wanted a single nodeschool for just my organization. I'm not trying to be misleading. 

I just don't realize why I can't have one single repo for my entire organization. 

I'm not going to be attractive to people who already know what a nodeschool is. I'm going to be marketing to people who don't even know of nodeschool. But it seems that is somehow a conflict of interest. 

So I can use part of the nodeschool materials, just not the github features (i.e. can't have a github repo)? Is that accurate? 

----- On Mar 15, 2015, at 11:19 AM, Jason Rhodes <notifications@github.com> wrote: 



Honestly, @martinheidegger , I don't think this use case is a great one for multiple chapters. 



a commercial training enterprise with 6 company locations and an online presence as well 



No reason the nodeschool materials can't just be used without needing to set up chapter repos, which I think would be misleading.

**Comment by sjledet** [comment]
Yes. Thanks. That now makes sense. I can use nodeschool curriculum. I can't have a nodeschool chapter. 

Thanks. Sorry for the previous email. I read that one before this one. 

----- On Mar 15, 2015, at 10:30 AM, Jason Rhodes <notifications@github.com> wrote: 

You are absolutely welcome to use the NodeSchool curriculum and materials however you like. Fork any repo or create your own, then use them for whatever you're company is trying to do. Chapters, up to now, have been location based, usually free or low cost community-run orgs that have events on a semi-regular basis in one geographic area. So your use case might not be a chapter but you don't need to be a chapter to use nodeschool materials. 

Does that make sense?

**Comment by jasonrhodes** [comment]
Yeah just to be clear, "can't" is probably a little strong, but my preference is that chapters stay what they mostly are now, which is community-run free or low-cost events based in geographic area. If chapters expand to represent code schools in multiple cities, I think it's probably just confusing. 

And also, you can have any GitHub repos you want! The ones attached to this org are mostly for chapters, but you can fork any repo you want on your own GitHub account and use it for whatever you like.

Good luck!

**Comment by martinheidegger** [comment]
@jasonrhodes A professional school is in the end nothing but a person teaching other people things. Which is - aside from the money - not different from what Nodeschool does. @sjledet hosts events at various locations. At those locations there may be people interested in the nodeschool. Not having them attend because its expensive is I think less problematic than definitely attending because there is nothing related to nodeschool. Seeing as people that will come to @sjledet's events are effectively already "learning together nodeschool in a place" he might as well open a chapter.

**Comment by blakmatrix** [comment]
> Here are some of the tenets of the community:
* there is no top-down leadership structure. we have thousands of students, hundreds of chapter organizers, and a small group of central admins who keep the website running etc.
* chapters should experiment with new ways to engage their community, and share approaches with other chapters over time
* events should be affordable and should strive towards diversity and inclusiveness
* we are 100% open source and like to license things as open source/creative commons
...
* We are a 100% volunteer run international open source community.

Here are a few loosely similar existing groups:
https://github.com/nodeschool/Rapid_CitySD
https://github.com/nodeschool/Delhi-NCR
https://github.com/nodeschool/princeton

However each of these are loosely location based... unless i've missed something, and these tenets are shared, I don't see a problem either way, just because the tenet is "should strive" doesn't mean it must.

**Comment by jasonrhodes** [comment]
This all makes sense. My thoughts were more about the perception that you
have to start a chapter and get a /nodeschool/<name> repo in order to use
the nodeschool materials in any way, which isn't true at all. It'd be good
for us to clarify why someone might want to create a chapter, and what we
loosely expect chapters to do.

For instance, if a company starts a chapter in 10 US cities because they
are doing a programming curriculum that happens to use the nodeschool
workshoppers in addition to a bunch of other learning tools, and doesn't
really hold regular events in those cities or have much interest in working
with the local community, then not only is it a bit strange but if someone
comes along and wants to start a community chapter in that city, it's
already taken but for a pretty wildly different use, which doesn't make a
lot of sense.

So yeah, less about "you can't do this" and more about clarifying things a
bit.

**Comment by martinheidegger** [comment]
Not sure where to go from here ...

**Comment by finnp** [comment]
I feel like this is resolved since @sjledet wants to use the materials just like that. If I'm wrong about it, just reopen it.
