### ISSUE TITLE
spam-ish event entry

### ISSUE THREAD

**Issue by Trott** [nodeschool/organizers#175]
3/22/2015 entry for Bangaluru Node School has a link to http://amt.in/node-school.html which redirects to a page that contains no information whatsoever about NodeSchool but does contain plenty of exhortations to hire their agency.

It's possible that the node-school.html page used to exist or something, but this is a future event so it should still be there, so that's certainly suspicious.

**Comment by martinheidegger** [comment]
@jlord What do you think of adding an email field to the event form? In case there is a question, we can contact them. Without valid email, or answer to an email within 2 days to a question, we just delete the entry?

**Comment by blakmatrix** [comment]
+1 required email and maybe some messaging to indicate we'll get in contact if there are any questions.

**Comment by jlord** [comment]
Spam is such a bummer :confused: 

Yeah, I'm all for adding an email field, we can make a note that we won't publish the email (so that they person who gives up their email doesn't have to worry about getting spam themselves), that we'll just use it for our own verifying-you're-real purposes.

It would be nice to automate it though, waiting 2 days on an email reply and then deleting could get tedious. 

Will spammers also enter spammy emails though? Is entering an email alone not enough to know if it is spam?

**Comment by jlord** [comment]
I'm looking at the form itself now... it doesn't seem like they provide a are-you-human option, which is also a bummer.

I'm also looking to see how to add someone to the form. @martinheidegger since you have access to the spreadsheet, does that allow you to click some how to the form that generates it?

**Comment by jasonrhodes** [comment]
@jlord there is a "request edit access" button on the form even if you already have access to the sheet, FYI

**Comment by Trott** [comment]
I could be totally wrong about this, but I don't think the problem is with automated bots so I don't know that there's much to be gained (at least not immediately) by trying to put together a CAPTCHA substitute. I suspect all of these entries were entered by hand, perhaps even by well-meaning people sometimes.

**Comment by Trott** [comment]
Of course, on the other hand, it's probably only a matter of time before LOW3zt C05t for V|A&RA shows up as an event...

**Comment by martinheidegger** [comment]
@Trott I am going to look forward to see that. Perhaps we should change from google docs to a github based system? This way every event would be a PR?!
