### ISSUE TITLE
New chapter for Arizona (Phoenix, Tempe, Scottsdale)

### ISSUE THREAD

**Issue by ryansorenson** [nodeschool/organizers#217]
Hi, I would like to start a nodeschool chapter for Arizona. I am @dollarshots on twitter and work at GoDaddy. I will be co-organizing this chapter with someone else at GoDaddy but unsure of who quite yet. I have been using Node.js for 1 month and want to start a nodeschool chapter for others learning like me, and mentors looking to connect.

**Comment by maxogden** [comment]
@ryansorenson Hi Ryan! We typically like to have a couple organizers from a community to start a chapter, let us know when you get some other folks to help out :D

**Comment by maxkorp** [comment]
@ryansorenson I had been looking to organize a chapter for phoenix for close to a year now, but the other person who was involved had to drop out, and I haven't had the time to fly it solo. I actually deleted our (empty) repo under the org, so that someone else would have it available to use. I'm pretty near by, and would be glad to help.

**Comment by SomeoneWeird** [comment]
Sweet. If you guys want to start doing something together I'd be more than happy to set up a chapter :tada:

**Comment by michaelhwan** [comment]
Hi @ryansorenson I'm in Phoenix area as well.

**Comment by iancrowther** [comment]
+1

**Comment by michaelhwan** [comment]
@maxkorp where did you host NodeSchool before?

**Comment by iancrowther** [comment]
what's the plan then chaps? are we starting a new chapter or can I close this?

**Comment by martinheidegger** [comment]
Since there has been no response I am assuming it didn't work out. Closing this issue. Please reopen if that was prematurely.
