### ISSUE TITLE
Why do you think NodeSchool has been successful so far?

### ISSUE THREAD

**Issue by jasonrhodes** [nodeschool/organizers#226]
Hey organizers! I'm giving a modified version of my Empire Node talk from last year where I talked about "Open Source Collaborative Community Learning" as it relates to NodeSchool. I'm curious to hear from you all who have been running events:

* What's interesting about how NodeSchool teaches people things?
* Is it successful in teaching? Why? 
* Do you think there are other events or communities that are similar, either in tech or in other fields? Any examples?
* Any other stories or thoughts on "the NodeSchool format" that you might have. 

Thanks, I appreciate any and all thoughts and comments!

**Comment by jiripech** [comment]
Two main reasons for me:
1) The wide area that nodeschool covers so far (and the fact it's still growing).
2) _Do your adventures yourself, get it automatically checked and ask if you need something_ is the best learning style for the introvert IT guys.

**Comment by louisnk** [comment]
Hey Jason! Thanks for being such a driving force, and not relenting.

NodeSchool is interesting because it challenges people with things in bite-sized pieces (sometimes big bites) and builds confidence in skills over time.

I think it's successful in teaching people because it allows for every learning style in one environment, and mentors are always really eager to help.

CoderDojo (for kids) is similar, but it's a bit more structured and starts out with a lesson each time.

Where will you be giving the talk/will it be online afterwards?

**Comment by llkats** [comment]
Speaking from my experience of helping to organize the SF chapter with @jedireza since February (three great events and counting!):

- **open organizing**: at first, organizing everything in the repository felt a little vulnerable and scary (at least to me!) but it was a great way for people to jump in and help out with what they could do. I believe this helped lead to greater support and more volunteers.

- **chill atmosphere**: the learn-at-your-own-pace nature of the workshoppers gives a very laid-back atmosphere. People use their own computers, so they're already comfortable with the machine they're trying to learn something new on. Having mentors available means that no one is ever stuck for too long. Attendees can and do chat amongst themselves, and help each other out. All of this creates a collaborative, equitable atmosphere.

- **cool stickers**: self-explanatory

I think that Nodeschool is successful in teaching programming because it shows beginners that they can program with the comptuers/tools they have at hand, and introduces them to a community of support as well. In my experience, the JS community has been especially welcoming, and the Nodeschool events put people who are already active in the community in direct contact with people who want to know more. 

Some years ago, back in Chicago, I went to a Railsbridge event, and I think they are very similar events. Informal pairing and/or getting in-person help on an app is invaluable to newcomers and can't be replicated through an automated course. What's more, attendees can get exposure to different ways of doing things and different tools, and can grow that way too.

What has been most interesting to me about Nodeschool is the framework it provides for people who want to help others learn. It's a central concept that gives experienced devs a way to give back and grow the community in a very open way, and that, to me, is the most special sparkly amazing part of Nodeschool. :grin: :dancer: :smile_cat:

**Comment by jedireza** [comment]
@llkats said it so well. I also like the fork-ability of the whole thing. It's great that chapter self organize and manage.

**Comment by mikeal** [comment]
TLDR thus far; NodeSchool has succeeded in every area it has successfully reduced a barrier to entry. The process of identifying new barriers to learning and contributing and tearing them down is ongoing :)

One thing that hasn't been mentioned yet that I think has also been key is that NodeSchool doesn't just onboard you into programming it dumps you right in to open source culture via GitHub which has an existing support system of developers to engage with.

**Comment by olizilla** [comment]
The events seem to work well for lot's of different groups. Them that prefer to work alone, and those that prefer to collaborate, seem to get on fine in the same space. 

The super keen do workshops in advance and turn up to events with questions. The recently enlightened leave with a pile of follow on challenges as homework. The totally stuck turn up with a bork'd node install and at least leave with a working workshopper.

From the organisers side, having tons of "material" reduces the burden on mentors; they can basically turn up on the day and be helpful (similar to how CodeSchool works in the UK).

One thing that I've seen work in nodeschool and other volunteer projects is, people seem to feel more comfortable when they get a sense that organisers and events have no ulterior motives... like... it's not a hiring or marketing gimmick, it's not "a trap" kinda of thing. Non-commercial. Just some people with similar interests that you might want to talk to, which can be tricky for people to find, or feel confident enough to engage with, otherwise.

Definitely a +1 on the forkability / github style / minimal centralisation. If you have the energy to put on an event, you have the power to do so, and we're all on here to help however we can. You get to **create** your own local meet up while feeling part of something bigger. You're supported not constrained.

**Comment by martinheidegger** [comment]
I think this question has been answered, as part of a cleanup I am closing this issue. Please reopen if you feel that this question is still pressing.
