### ISSUE TITLE
Mannheim nodeschool

### ISSUE THREAD

**Issue by cookiengineer** [nodeschool/organizers#241]
We were starting the nodeschool chapter for Heidelberg last week and it was a success. The issue around here is that communities are splitup, despite under 20km distance. So we try to get them together by also founding a nodeschool Mannheim and organizing both events in even/uneven week dates, so they are kind of forced to get to know each other ;)

Let me know if that makes sense or if the area name is a better name (like nodeschool Rhein-Neckar?). I assumed only city-based names are allowed.

I'm already in the nodeschool organization, just wanted to ask what is appropriate to not conflict with the scheme :)

**Comment by maxogden** [comment]
this is a good question. the two cities are quite close, so it would be nice to have one team. if Rhein-Neckar is the best name for the two cities then I would go with that

**Comment by martinheidegger** [comment]
The foremost purpose (imho) of chapters it to communicate to members that there is a place nearby where people meet. If the distance is too small i.e. < 15km (9.3miles) then I would just count it as "same place" since the people probably live/work not exactly at that location where the events are held. Just some idea but: How about we allow homepage sections for "areas" where some chapters say that they work closely together?

**Comment by finnp** [comment]
Okay apparently you used Rhein-Neckar. Seems like a good choice :relaxed: I should visit you sometime in summer. Such a beautiful place to bike :bike:
