### ISSUE TITLE
Third Party Permissions

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/organizers#244]
Should I enable Github's Third-party application access policy on the nodeschool org?

What impact might this have?  I don't want to just flick the switch

cc' @nodeschool/international-day 

^^ this is the most comprehensive org list, sorry to spam

**Comment by yoshuawuyts** [comment]
looks like it makes things safer, so +1 from me. Less chance of weird things happening when anyone in the nodeschool org logs into a random website through GitHub.

**Comment by Sequoia** [comment]
:-1: I have 2FA on my account but the impact it will have is "increasing barriers to participation." This org is open by design, we will add anyone nodeschool/owners who asks, no? So adding extra security to prevent "unauthorized access" seems sorta silly :yum:

That said I use it & I recommend everyone does, but I don't want to compel other people to outside of a work environment.

**Comment by Sequoia** [comment]
Sorry I completely misunderstood the comment & apparently cannot read. pls ignore my last comment :)

**Comment by iancrowther** [comment]
@Sequoia lol

**Comment by iancrowther** [comment]
it makes sense to me, I'm just concerned that the impact will be far reaching as its a big 'ol org now

**Comment by iancrowther** [comment]
so trying to communicate and minimise the backlash

**Comment by iancrowther** [comment]
@mikeal pls re-add me to core so I can action this

**Comment by SomeoneWeird** [comment]
This was done a while back.

**Comment by iancrowther** [comment]
Perfect
