### ISSUE TITLE
New chapter for Perth, Western Australia

### ISSUE THREAD

**Issue by nii236** [nodeschool/organizers#247]
Hi, I would like to start a nodeschool chapter for Perth, Western Australia. I am @nii236 on twitter and work at [The Frontier Group](http://www.thefrontiergroup.com.au). I will be co-organizing this chapter with @miqid. I have been using Node.js for 3 months and would like to help others learn as well.

**Comment by tgfjt** [comment]
@nii236 @miqid
Hi! I added you the chapter-owner list.
Please follow https://github.com/nodeschool/organizers/blob/master/README.md to setup the chapter!

:tada:

**Comment by maxogden** [comment]
@tgfjt hey since the new team changes we made last night we have to have an Owner create the repo for them now, and add that repo to the list here https://github.com/orgs/nodeschool/teams/chapter-organizers/repositories. i'll add you to Owners so you can do it in the future. We hopefully will find a better way to do it in the future.

**Comment by maxogden** [comment]
@nii236 the new repo is here: https://github.com/nodeschool/perth

**Comment by tgfjt** [comment]
@maxogden  uh okay. thanks for your helping! I'll check & think about it.

**Comment by nii236** [comment]
Thansk all!
