### ISSUE TITLE
What age groups has Node School been held?

### ISSUE THREAD

**Issue by leftieFriele** [nodeschool/organizers#299]
I want to create a code club in my local community and I think Nodeschool is a great platform for learning. However I'm a bit uncertain as to whats the earliest anyone has tried Nodeschool on kids?

**Comment by iancrowther** [comment]
in London its been adults ony, but im keen to open it up to kids as well

**Comment by leftieFriele** [comment]
I guess the first lesson is missing, which would be "What is the command
line" as that is not as easy of you've never seen it.
Is there any material on that anywhere online?

**Comment by maxogden** [comment]
@leftieFriele YO!

+1 to nodeschool kids edition. I'm not sure if anyone has done it for kids yet to be honest, but we're long overdue for that

Maybe some game oriented workshoppers are in order?

**Comment by leftieFriele** [comment]
I've got no idea what's the best material :)
I think you'd first need an intro to computers and command line and generic
commands. If not they're going to have a really hard time using
workshopper, I think.

I wrote a quiz game about English soccer when I was a kid (in basic) :)
perhaps quiz game workshopper would be good?

**Comment by iancrowther** [comment]
+1

**Comment by yangwao** [comment]
I think in Barcelona there will be NodeSchool kids organized by Patrik

**Comment by iancrowther** [comment]
oh sweet

**Comment by martinheidegger** [comment]
The Coder Dojos do use JavaScript to train kids (they might be using NodeSchool material?)

**Comment by a0viedo** [comment]
We organized a NodeSchool event for kids between 13 and 18 and it went great. It had identical dynamic like any other event, we had the advantage that they were part of an organization ([Puerta18](http://www.puerta18.org.ar/)) that gives technology courses to kids regularly, so they had strong background on computers and logic.

cc @mgtitimoli

**Comment by jpwesselink** [comment]
in Haarlem the ages range from 19 to 50-ish. We haven't planned on focussing on 13 - 18 yet, but I think it's a great idea.

**Comment by No9** [comment]
Calling @noelking who mentioned he was putting some node pieces together for coderdojo 
Which might be useful

**Comment by mgtitimoli** [comment]
One aspect that could be not so engaging for ages below of 15 is the absence of a graphical environment, since I believe they are too used to interact with this kind of UIs. Nevertheless,  I also believe this would be like this for kids they haven't coded yet. In our case (https://github.com/nodeschool/organizers/issues/299#issuecomment-166382817), we have the advantage that most of the kids that participated have done some coding previously. And following this line of thought, for ages under of 15, I would recommend an alternative where they can see what they are doing, a game, or some approach similar to Logo programming language, since IMHO workshoppers are too abstract for kids that haven't coded yet, to engage with the flow.

**Comment by martinheidegger** [comment]
Opened a general "champion wanted" issue for data processing which mentions age groups. https://github.com/nodeschool/organizers/issues/387

Closing this issue atm. looking for contributor in the other thread.
