### ISSUE TITLE
Wellington NZ Chapter

### ISSUE THREAD

**Issue by vimto** [nodeschool/organizers#32]
Hi, 

I'd like to start a nodeschool chapter for Wellington NZ.

I'm @vim on twitter, and I work at Atomic Software building software for designers using JavaScript and Node. I also co-run the [Wellington JavaScript](http://meetup.com/WellingtonJS/) meetup.

I've been using Node.js since professionally since the start of the year, and I'm keen to help other locally get started.

Thanks!

**Comment by ahdinosaur** [comment]
hey @vimto @chilts, what's the status on this?

i've been hosting a weekly hack night at [EDA](http://devacademy.co.nz/) around learning and teaching Node.js [since February](http://www.meetup.com/Enspiral-Dev-Academy-Meetup/events/220326043/), i was wondering if this could become the "official" Wellington NodeSchool chapter, where the emphasis is less about [large one-shot events](http://nodeschool.io/christchurch/) and more about a space to hack with Node.js friends every week.

i'm keen to setup a website and all that, although i appreciate if anyone wants to help. :)

**Comment by vimto** [comment]
Hey @ahdinosaur, I posted my original message a while ago with the intent of organising a regular nodeschool event in Welly. 

Unfortunately I haven't had the time to do so, so i reckon it makes sense to use this space for the one that you're already organising. I've added you to the repo @ahdinosaur.

Sound good @chilts?

**Comment by ahdinosaur** [comment]
sweet, got the invite, thanks @vimto. :)

**Comment by ahdinosaur** [comment]
@vimto, is it possible to be added as an Owner? would be nice to edit the repo description and add more team members. cheers.

**Comment by vimto** [comment]
Sure, didn't realise you weren't. Done.

**Comment by ahdinosaur** [comment]
ta. :smile:

**Comment by chilts** [comment]
Sorry, I haven't been active in any NodeSchool stuff (apart from being added here), so tbh I have no brownie-points here ... you guys look like you're all trucking anyway. :) Thanks @vimto and @ahdinosaur.
