### ISSUE TITLE
New Chapter for Philippines (nationwide)

### ISSUE THREAD

**Issue by ledsusop** [nodeschool/organizers#329]
We would like to formally start a chapter in the philippines for members of this group:
https://www.facebook.com/groups/node.jsphilippines/

and this meetup group:
http://www.meetup.com/Node-js-Philippines/

I am a staff engineer from Walmart eCommerce in Sunnyvale, CA but regularly go home to Philippines and is currently trying to ramp up local group activities related to node.js

I am also aware that the nationwide scope is bigger than preferred, but the members of the groups mentioned are actually not geographically bound to a specific city or metropolis and we may potentially hold the nodeschool events in different areas.  Please reconsider.  If really not doable, then we will have to settle with Nodeschool Metro Manila

**Comment by martinheidegger** [comment]
@ledsusop First off: it is awesome that you want to start a chapter! However: we usually have the rule that a chapter should not describe a geographic location bigger than 20km radius since a chapter, by definition, is usually there to organise **local** events. Not everyone of the Philippines will be able to get to Manila for a NodeSchool event. Add to the point: recently @levint started a cebu chapter which means there is already a different chapter in the Philippines. Know that you can freely use this repository and the [gitter chat room](https://gitter.im/nodeschool/organizers) for inter-chapter organization. With that in mind: should i setup a manila chapter?

**Comment by ledsusop** [comment]
yes please

**Comment by martinheidegger** [comment]
Sorry for the delay @ledsusop I have been busy but I found out that there was a Manila Chapter request quite some time ago. I invited you to the manila group and chapter-organizers group. I hope you can set up things this way. https://github.com/nodeschool/manila

**Comment by tmlaughlinjr** [comment]
@ledsusop We're setting up a NodeSchool for the 16th with Manila JavaScript, Amagi Academy, and NuWorks. Can we work together to co-operate to make the Manila chapter? Unless @martinheidegger has suggestions?

**Comment by iancrowther** [comment]
closing as connections have been made..

good luck with the event and have fun
