### ISSUE TITLE
Change in date for 9/29/2016 Nodeschool Dublin to 06/10/2016 

### ISSUE THREAD

**Issue by johnbrett** [nodeschool/organizers#381]
Hi Nodeschoolers.

The date of this meetup had to be moved from 9/29/2016  to 06/10/2016 due to a clash with a meetup. Can this be updated on the nodeschool website? (Can do it myself either if someone points me in the right direction!)

Apologies for this, and thanks in advance!

**Comment by martinheidegger** [comment]
Hello @johnbrett 

Only a few people have access to the events spreadsheet (in order to prevent accidental deletions, modifications). Usually after adding an event it should give you an URL to make changes at it yourself later on. Raising an issue here is 1A okay though. I took the liberty to already modify the date. Is it correct right now?

best regards
Martin

**Comment by johnbrett** [comment]
That's perfect Martin, thanks a mil!

Might be worth updating this on the site if you don't want people directed here to update dates ;)

![image](https://cloud.githubusercontent.com/assets/4015939/18689717/79a4797e-7f82-11e6-92e4-51f6cf088d9b.png)

**Comment by martinheidegger** [comment]
@johnbrett There is a mention at the end of the form that states to keep the link for future edits. I think it should okay as-is (not happening so often)
