### ISSUE TITLE
New Chapter: Nodeschool Abuja Nigeria

### ISSUE THREAD

**Issue by savicsly** [nodeschool/organizers#472]
Hi, I would like to start a nodeschool chapter for Abuja NG. I am @savics on twitter and work at Bingham University. I have been using Node.js for About a year now and i believe teaching will help me learn better so i would like to help others learn as well and in the process learn better. Although there is one chapter that goes with the name Abuja, but it has been dormant since creation and the creator inactive, hence the need to start this new one.

**Comment by riyadhalnur** [comment]
Hi @savicsly, that's awesome. Since a chapter already exists, I would recommend contacting the current maintainer and discuss letting you take over.

**Comment by savicsly** [comment]
hi @riyadhalnur i have done so already, but no response, he has been inactive on github for quite a while now.

**Comment by riyadhalnur** [comment]
I've added you to the abuja team.

**Comment by savicsly** [comment]
Thank you

**Comment by riyadhalnur** [comment]
Closing the issue then. Please feel free to re-open if premature.

**Comment by ldbraun** [comment]
Hello @savicsly, Welcome to Nodeschool Abuja. my names: Braun Okoi Boniface and my handle @ldbraun. I have been using nodejs for 3 years + now and have taught and created proprietary projects with it as well. 

The Chapter has been inactive for some time now due to reasons below:

1. Each time I try to commit changes to the chapter I get errors which interprets that I don't have write and edit permissions which @riyadhalnur has tried to fix.

2. I haven't been around and stable for quite sometime too as I traveled for a project and one of my certification exams.

its quite a pleasure and a thing of joy to have you on this chapter and I believe, with our joined effort we can move and create a bigger community. Please feel free to contact me using the handle above so we can discuss further.

**Comment by ldbraun** [comment]
@nodeschoolbot help

**Comment by riyadhalnur** [comment]
Was the abuja repo deleted?
