### ISSUE TITLE
Start new chapter, Abuja Nigeria.

### ISSUE THREAD

**Issue by inidaname** [nodeschool/organizers#508]
Hi, I would like to start a nodeschool chapter for Abuja, Nigeria, I am **@inidaname** on twitter and work at [**ADP Nigeria**](actiondemocraticparty.org). I will be co-organizing this chapter with [@devamaz](https://github.com/devamaz). I have been using Node.js for 14 months and would like to help others learn as well. *

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-user inidaname

**Comment by riyadhalnur** [comment]
I have added @inidaname to the `chapter-organizers` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team abuja

**Comment by riyadhalnur** [comment]
I have encountered an error doing this :(

```
Error: Bad status: 422
    at Request._callback (/home/nowuser/src/server.js:344:17)
    at Request.self.callback (/home/nowuser/src/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/home/nowuser/src/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-team abuja

**Comment by riyadhalnur** [comment]
I have created @nodeschool/abujateam

**Comment by riyadhalnur** [comment]
@nodeschoolbot create-repo abuja

**Comment by riyadhalnur** [comment]
I have created a new repo called [abuja](https://github.com/nodeschool/abuja)

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user abuja inidaname

**Comment by riyadhalnur** [comment]
I have invited @inidaname to the `abuja` team.

**Comment by riyadhalnur** [comment]
@nodeschoolbot add-team-user abuja devamaz

**Comment by riyadhalnur** [comment]
I have invited @devamaz to the `abuja` team.

**Comment by riyadhalnur** [comment]
Hi @inidaname, I created the Abuja team and repo and invited all of you. Please accept the invite and let me know if everything is good on your side. Have fun and welcome again to the NodeSchool family! 😃

You can find it at https://github.com/nodeschool/abuja. If you'd like to add members to your chapter's team, you can use @nodeschoolbot to do so.

Take a look at https://github.com/nodeschool/organizers/wiki to get you started.

**Comment by riyadhalnur** [comment]
Here is what I can do for you:

* `help` - shows this help
* `create-repo {name}` - creates a nodeschool repo
* `add-user {username}` - adds a user to the `chapter-organizers` team and the org
* `create-team {team}` - creates a new team
* `add-team-user {team} {username}` - add a user to a specific team

**Comment by ldbraun** [comment]
Hello Riyadh Al Nur,

I noticed that you just re created the Nodeschool/Organizers Abuja Chapter

I am @ldbraun and the organizer of the chapter. Why was the chapter re created?

Thank you.
Best regards.

Braun Boniface
CTO - Chief Technology Officer.
Okoi Studios
From: Riyadh Al Nur
Sent: Saturday, 10 February 2018 10:30
To: nodeschool/organizers
Reply To: nodeschool/organizers
Cc: Subscribed
Subject: Re: [nodeschool/organizers] Start new chapter, Abuja Nigeria. (#508)



@nodeschoolbot<https://github.com/nodeschoolbot> add-user inidaname

**Comment by riyadhalnur** [comment]
Hi @ldbraun, I remember asking why the original chapter was deleted last year on #472. The deletion was not from our side and so I presumed it had been deleted by the chapter organisers themselves since there was no follow-up comment to mine.

**Comment by ldbraun** [comment]
‎Didn't delete the chapter. I remember also raising an issue concerning a user asking to recreate the chapter and you directed the user to get in touch with me and I did reached out to him and didn't get any response since then. So, I wonder why the chapter is now recreated and controlled by another user?

Braun Boniface
CTO - Chief Technology Officer.
Okoi Studios
From: Riyadh Al Nur
Sent: Saturday, 10 February 2018 13:15
To: nodeschool/organizers
Reply To: nodeschool/organizers
Cc: Braun Okoi Boniface; Mention
Subject: Re: [nodeschool/organizers] Start new chapter, Abuja Nigeria. (#508)



Hi @ldbraun<https://github.com/ldbraun>, I remember asking why the original chapter was deleted last year on #472<https://github.com/nodeschool/organizers/issues/472>. The deletion was not from our side and so I presumed it had been deleted by the chapter organisers themselves since there was no follow-up comment to mine.

**Comment by riyadhalnur** [comment]
Since the chapter did not exist anymore, the bot recreated it. Had it been there, the bot would have failed to do so. From what I remember, the chapter was deleted and hence my comment on the issue mentioned and there was no follow-up. I apologise for the misunderstanding here. I can re-invite you back to the chapter team and possibly also sort this out with @inidaname.

**Comment by ldbraun** [comment]
OK. So what does this really mean now to the work I and my team are doing?

Braun Boniface
CTO - Chief Technology Officer.
Okoi Studios
From: Riyadh Al Nur
Sent: Saturday, 10 February 2018 13:25
To: nodeschool/organizers
Reply To: nodeschool/organizers
Cc: Braun Okoi Boniface; Mention
Subject: Re: [nodeschool/organizers] Start new chapter, Abuja Nigeria. (#508)



Since the chapter did not exist anymore, the bot recreated it. Had it been there, the bot would have failed to do so. From what I remember, the chapter was deleted and hence my comment on the issue mentioned and there was no follow-up. I apologise for the misunderstanding here. I can re-invite you back to the chapter team and possibly also sort this out with @inidaname<https://github.com/inidaname>.

**Comment by riyadhalnur** [comment]
The work you and your team have done and/or are doing should not be affected by this misunderstanding ideally. There can exist multiple co-organisers for one chapter and, working and learning together is what NodeSchool is about. I have re-added you to the team.

**Comment by ldbraun** [comment]
But how? I as I see am not the current owner/organizer of the chapter.

Please can you see the issue #364?

Thanks

Braun Boniface
CTO - Chief Technology Officer.
Okoi Studios
From: Riyadh Al Nur
Sent: Saturday, 10 February 2018 13:33
To: nodeschool/organizers
Reply To: nodeschool/organizers
Cc: Braun Okoi Boniface; Mention
Subject: Re: [nodeschool/organizers] Start new chapter, Abuja Nigeria. (#508)



The work you and your team have done and/or are doing should not be affected by this misunderstanding ideally. There can exist multiple co-organisers for one chapter and, working and learning together is what NodeSchool is about. I have re-added you to the team.

**Comment by riyadhalnur** [comment]
I made you the team maintainer.

**Comment by ldbraun** [comment]
Ok. Not sure what that means?

Braun Boniface
CTO - Chief Technology Officer.
Okoi Studios
From: Riyadh Al Nur
Sent: Saturday, 10 February 2018 14:03
To: nodeschool/organizers
Reply To: nodeschool/organizers
Cc: Braun Okoi Boniface; Mention
Subject: Re: [nodeschool/organizers] Start new chapter, Abuja Nigeria. (#508)



I made you the team maintainer.

**Comment by inidaname** [comment]
@ldbraun I will be very happy to work with you on this.

**Comment by ldbraun** [comment]
@inidaname Y'aii. no problema. you're welcome. open source is all collaborations.
