### ISSUE TITLE
for a better society

### ISSUE THREAD

**Issue by hrayatnia** [nodeschool/organizers#78]
what do you think about nodeschool's global certificate??
or create a global project or something like this
@maxogden @jasonrhodes and other

**Comment by martinheidegger** [comment]
The NodeSchool is a community effort. That makes me think that all the material here is basically a suggestion of how you can do things: "You can use workshopper to learn node", "You can write your own workshopper", "You can host it in a cafe" etc. 

We are basically preparing material for making it easier to hold an actual event. But the event needs to take care of other things too and has all the power to deviate. 

Having a good credential system is work to setup and work to maintain. I can see a good reason why the community should work on this together to make it easier for the chapters to certify someone. "You can use this to certify in your area". Since it is a need of many schools around the world I am strongly for opening the NodeSchool up to provide a system that can be used by the schools/organisations in question.

Note: To me a good "certificate system" should also include a good "authority group system". Someway to make clear that Certificate X was given by Authority Y.

**Comment by Sequoia** [comment]
As pointed out:
1. Certs can be good & valuable
2. Running cert authority with the attendant stuff (proctored exams? certificate authenticity verification, etc.) is *probably* too much for a volunteer org

If someone wants to set up a nodeschool certificate program, that's awesome, but probably outside the scope of the nodeschool project itself

# Proposal: 3rd Party Certification
Someone who wants to take this on can/should set up a website, research how to do this, figure out all the details, figure out how to farm out to other trainers, and make a small business of it.  In this vision, the certificates wouldn't be "nodeschool.io certified" they'd be "Xiao's Nodeschool Academy Certified." There are plenty of models for Libre<->Paid, see Testling free vs. service, (php) composer/packagist vs. Toran etc..

Trustworthy certificates would be a great value-add (worth paying for) that would complement nodeschool, but are not, imo, part of the "nodeschool mission." Somebody go for it! :smile_cat: :moneybag: :page_with_curl:

**Comment by martinheidegger** [comment]
I find that "3rd Party Certification" very charming. It would be an incentive for people that do this sort of program that the NodeSchool will refer to them.

**Comment by yoshuawuyts** [comment]
It might be interesting to hook into Mozilla's Open Badges program. That way at least the hosting of certifications can be part of something that's already established -- http://openbadges.org/

**Comment by martinheidegger** [comment]
@yoshuawuyts awesome!

**Comment by martinheidegger** [comment]
I am in favour of closing this for an issue of "Lets create some badges for openbadges" :+1:

**Comment by martinheidegger** [comment]
And... closing this issue.
